# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Small%20Slant&t=Site%20Settings
#
#     _____ __        ____    __  __  _
#    / __(_) /____   / __/__ / /_/ /_(_)__  ___ ____
#   _\ \/ / __/ -_) _\ \/ -_) __/ __/ / _ \/ _ `(_-<
#  /___/_/\__/\__/ /___/\__/\__/\__/_/_//_/\_, /___/
#                                         /___/
#
title: Jekyll NetlifyCMS test site
author:
  name: peteredwards
  email: p.l.edwards@leeds.ac.uk
description: >
  This is a test GitHub Pages site which uses the 
  University of Leeds jekyll theme and NetlifyCMS

google_analytics: "GTM-WJPZM2T" # set to Google Tag manager ID

# contact information
contact:
  organisation: University of Leeds
  # Address
  address:
    street: Woodhouse Lane
    locality: Leeds
    region: West Yorkshire
    postcode: LS2 9JT
    country: UK
  telephone: +44 0113 243 1751
  email: 

  # Social media links
  social_links:
    # facebook: uol
    # instagram: uol
    # linkedin: uol
    # medium: uol
    # twitter: uol
    # weibo: uol

    # either a youtube user
    # youtube: uol
    
    # or a youtube channel
    # youtube_channel: 
    # youtube_channel_name: 

# Blog settings
paginate: 10
paginate_path: "/blog/page:num/"
show_excerpts: true
# Date format - this is overridden in post-list-item.html
date_format: "%A %-d %b, %Y"
permalink: pretty

exclude:
  - README.md
  - LICENSE

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
