backend:
  name: github
  repo: peteredwards/uol-jekyll-netlify
  branch: main
  site_domain: silly-fermat-52243b.netlify.com

media_folder: "uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # preview pane doesn't understand Liquid(!)
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown"} 
  - name: 'navigation'
    label: 'Navigation'
    editor:
      preview: false
    files:
      - label: 'Navigation'
        name: 'mainmenu'
        file: '_data/navigation.yml'
        fields:
          - label: 'Main menu'
            name: 'mainmenu'
            widget: 'list'
            fields:
              - label: 'Name'
                name: 'title'
                widget: 'string'
              - label: 'Link'
                name: 'url'
                widget: 'string'
              - label: 'Subhmenu'
                name: 'items'
                widget: 'list'
                fields:
                  - label: 'Name'
                    name: 'title'
                    widget: 'string'
                  - label: 'Link'
                    name: 'url'
                    widget: 'string'
          - label: 'Quick Links'
            name: 'quicklinks'
            widget: 'list'
            fields:
              - label: 'Name'
                name: 'title'
                widget: 'string'
              - label: 'Items'
                name: 'items'
                widget: 'list'
                fields:
                  - label: 'Name'
                    name: 'title'
                    widget: 'string'
                  - label: 'Link'
                    name: 'url'
                    widget: 'string'
          - label: 'Footer menus'
            name: 'footermenu'
            widget: 'list'
            fields:
              - label: 'Name'
                name: 'title'
                widget: 'string'
              - label: 'Items'
                name: 'items'
                widget: 'list'
                fields:
                  - label: 'Name'
                    name: 'title'
                    widget: 'string'
                  - label: 'Link'
                    name: 'url'
                    widget: 'string'
